-- CreateTable
CREATE TABLE "Configs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "isCleaningNow" BOOLEAN,
    "lastCleaned" DATETIME,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

