name: Vercel Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      # Setup pnpm using the official action (version 8)
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # Setup Node.js with caching for pnpm dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Check pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --filter server --filter client --frozen-lockfile --config.confirmModulesPurge=false

      - name: Build workspaces
        run: pnpm --filter server --filter client run build

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${VERCEL_TOKEN}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Remove outdated Vercel builds
        run: vercel remove --safe --yes --token=${VERCEL_TOKEN} takemycode-dynamic-list
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
